### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by MRMYSTERY003** [Praneet9/Skin_Disease#2]
i cannot access the dataset, can you please provide any link for the dataset, if will be useful for me

**Comment by Praneet9** [comment]
The dataset was scraped from the website: https://dermnetnz.org/image-library
You can use the script `complex_webscraper.py` from the repo to download the dataset.
Here's a link to the subset of the data that can be used for experimentation - [Gdrive](https://drive.google.com/file/d/1ip643y-NwrQgPt-DIdtYm2f1TTcB54-g/view?usp=sharing)
